name: all_purpose_ml
channels:
- defaults
- conda-forge
dependencies:
- python=3.7,>3.6
- pip
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- jupyter
- pytorch
- tensorflow
- tensorboard
- scikit-learn
- pip:
      - gdown
      - networkx
      - xgboost
      - tensorflow-probability
      - dm-sonnet
