name: sci_informatics
channels:
- defaults
- conda-forge
dependencies:
- python=3.7,>3.6
- pip
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- jupyter
- pytorch
- torchvision
- tensorflow
- tensorboard
- scikit-learn
- rdkit
- pip:
      - networkx
      - xgboost
      - gdown
      - git+https://github.com/bp-kelley/descriptastorus
      - chemprop
      - biopython
      - openbabel
